/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.vistas;

import interfaz.controladores.CtrlVistaModificarLote;

/**
 *
 * @author Dani
 */
public class VistaModificarLote extends javax.swing.JFrame {

    private CtrlVistaModificarLote controlador;
    /**
     * Creates new form VistaModificarLote
     */
    public VistaModificarLote() {
        initComponents();
        controlador = new CtrlVistaModificarLote(this);
        cambiar.setVisible(false);
        error.setVisible(false);
        labelEstado.setVisible(false);
        labelFecha.setVisible(false);
        lotes.setVisible(false);
        estado.setVisible(false);
        fechaCreacion.setVisible(false);
        cancelarConfirm.setVisible(false);
        confirmar.setVisible(false);
        
        estado.addItem("Pendiente de Plantar");
        estado.addItem("Plantado");
        estado.addItem("En producción");
        estado.addItem("Fin de vida útil");
        estado.addItem("Eliminado");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        nombrePlanta = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        lotes = new javax.swing.JComboBox<>();
        labelEstado = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        labelFecha = new javax.swing.JLabel();
        cambiar = new javax.swing.JButton();
        cancelarConfirm = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        fechaCreacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modificar estado de lote:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        labelNombre.setText("Nombre de la planta:");
        jPanel4.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel4.add(nombrePlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarMousePressed(evt);
            }
        });
        jPanel4.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        consultar.setText("Consultar");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consultarMousePressed(evt);
            }
        });
        jPanel4.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, -1));

        error.setForeground(new java.awt.Color(255, 0, 51));
        error.setText("Error");
        jPanel4.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 300, -1));

        lotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotesActionPerformed(evt);
            }
        });
        jPanel4.add(lotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 90, -1));

        labelEstado.setText("Estado actual:");
        jPanel4.add(labelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        jPanel4.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, -1));

        labelFecha.setText("Fecha de creación:");
        jPanel4.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        cambiar.setText("Cambiar");
        cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiarMousePressed(evt);
            }
        });
        jPanel4.add(cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, -1));

        cancelarConfirm.setText("Cancelar");
        cancelarConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarConfirmMousePressed(evt);
            }
        });
        cancelarConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarConfirmActionPerformed(evt);
            }
        });
        jPanel4.add(cancelarConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        confirmar.setText("Confirmar");
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarMousePressed(evt);
            }
        });
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        jPanel4.add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, -1));
        jPanel4.add(fechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 13));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMousePressed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelarMousePressed

    private void consultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMousePressed
        error.setVisible(false);
        controlador.procesaEventoIntroduceNombrePlanta();
        
    }//GEN-LAST:event_consultarMousePressed

    private void lotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotesActionPerformed
        controlador.procesaEventoNuevoLoteSeleccionado();
    }//GEN-LAST:event_lotesActionPerformed

    private void cambiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarMousePressed
        
        cambiar.setVisible(false);
        error.setVisible(false);
        labelEstado.setVisible(false);
        labelFecha.setVisible(false);
        lotes.setVisible(false);
        estado.setVisible(false);
        fechaCreacion.setVisible(false);
        consultar.setVisible(false);
        cancelar.setVisible(false);
        cancelarConfirm.setVisible(true);
        confirmar.setVisible(true);
        
    }//GEN-LAST:event_cambiarMousePressed

    private void cancelarConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarConfirmMousePressed
        cambiar.setVisible(true);
        consultar.setVisible(false);
        labelEstado.setVisible(true);
        labelFecha.setVisible(true);
        lotes.setVisible(true);
        estado.setVisible(true);
        fechaCreacion.setVisible(true);
        cancelar.setVisible(true);
        
        cancelarConfirm.setVisible(false);
        confirmar.setVisible(false);
    }//GEN-LAST:event_cancelarConfirmMousePressed

    private void confirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMousePressed
        controlador.procesaEventoNuevoEstadoSeleccionado();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_confirmarMousePressed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarConfirm;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel error;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JLabel fechaCreacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JComboBox<String> lotes;
    private javax.swing.JTextField nombrePlanta;
    // End of variables declaration//GEN-END:variables

    public String getNombre() {
        return nombrePlanta.getText();
    }

    public void mostrarError(String msg) {
        error.setText(msg);
        error.setVisible(true);
    }

    public void añadirLote(String lote) {
        lotes.addItem("Lote " +lote);
    }

    public void mostrarLotes() {
        labelNombre.setVisible(false);
        nombrePlanta.setVisible(false);
        cambiar.setVisible(true);
        consultar.setVisible(false);
        labelEstado.setVisible(true);
        labelFecha.setVisible(true);
        lotes.setVisible(true);
        estado.setVisible(true);
        fechaCreacion.setVisible(true);
    }

    public void mostrarDatosLote(String fecha, String estadoSel) {
        fechaCreacion.setText(fecha);
        for (int i = 0; i < estado.getItemCount(); i++) {
            if(estado.getItemAt(i).equals(estadoSel)){
                estado.setSelectedIndex(i);
            }
        }
    }
    
    public int getLoteSeleccionado(){
        String lote = lotes.getSelectedItem().toString();
        int select = lote.charAt(lote.length()-1);
        return (select);
    }
    
    public int getEstadoSeleccionado(){
        return estado.getSelectedIndex()+1;
        
    }
    
    public int getIndexLoteSeleccionado(){
        return lotes.getSelectedIndex();
    }
}
