/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.vistas;

import interfaz.controladores.CtrlVistaActualizarFlores;

/**
 *
 * @author Dani
 */
public class VistaActualizarFlores extends javax.swing.JFrame {

    private CtrlVistaActualizarFlores controlador;
    /**
     * Creates new form VistaActualizarFlores
     */
    public VistaActualizarFlores() {
        controlador = new CtrlVistaActualizarFlores(this);
        initComponents();
        labelActual.setVisible(false);
        labelNueva.setVisible(false);
        estimacionActual.setVisible(false);
        estimacionNueva.setVisible(false);
        actualizar.setVisible(false);
        error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        confirmarEstimacion = new javax.swing.JButton();
        labelActual = new javax.swing.JLabel();
        labelNueva = new javax.swing.JLabel();
        estimacionActual = new javax.swing.JLabel();
        estimacionNueva = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Actualizacion de la estimación de flores:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));

        confirmarEstimacion.setText("Confirmar");
        confirmarEstimacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarEstimacionMousePressed(evt);
            }
        });
        getContentPane().add(confirmarEstimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 166, -1, -1));

        labelActual.setText("Estimación actual:");
        getContentPane().add(labelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 83, -1, -1));

        labelNueva.setText("Estimación nueva:");
        getContentPane().add(labelNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 118, -1, -1));
        getContentPane().add(estimacionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 83, -1, -1));
        getContentPane().add(estimacionNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 115, 49, -1));

        actualizar.setText("Actualizar");
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actualizarMousePressed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 166, -1, -1));

        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setText("Error");
        getContentPane().add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 146, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarEstimacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarEstimacionMousePressed
        controlador.procesaEventoComprobarFlores();
        controlador.procesaEventoMostrarEstimacion();
    }//GEN-LAST:event_confirmarEstimacionMousePressed

    private void actualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMousePressed
        controlador.procesaEventoActualizarEstimacion();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_actualizarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaActualizarFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaActualizarFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaActualizarFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaActualizarFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaActualizarFlores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton confirmarEstimacion;
    private javax.swing.JLabel error;
    private javax.swing.JLabel estimacionActual;
    private javax.swing.JTextField estimacionNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelActual;
    private javax.swing.JLabel labelNueva;
    // End of variables declaration//GEN-END:variables

    public int getIdLote() {
        return 1;
    }

    public String getCodigoPlanta() {
        return "B";
    }
    
    public String getEstimacion() {
        return estimacionNueva.getText();
    }

    public void mostrarEstimacion(String estimacion) {
        labelActual.setVisible(true);
        labelNueva.setVisible(true);
        estimacionActual.setVisible(true);
        estimacionNueva.setVisible(true);
        actualizar.setVisible(true);
        confirmarEstimacion.setVisible(false);
        estimacionActual.setText(estimacion);
    }

    public void mostrarError(String mensaje) {
        error.setVisible(true);
        error.setText(mensaje);
    }
}
