/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.vistas;

import interfaz.controladores.CtrlVistaModificarLote;

/**
 *
 * @author Dani
 */
public class VistaModificarLote extends javax.swing.JFrame {

    private CtrlVistaModificarLote controlador;
    /**
     * Creates new form VistaModificarLote
     */
    public VistaModificarLote() {
        initComponents();
        controlador = new CtrlVistaModificarLote(this);
        cambiar.setVisible(false);
        error.setVisible(false);
        labelEstado.setVisible(false);
        labelFecha.setVisible(false);
        lotes.setVisible(false);
        estado.setVisible(false);
        fechaCreacion.setVisible(false);
        cancelarConfirm.setVisible(false);
        confirmar.setVisible(false);
        
        for (int i = 1; i < 6; i++) {
            estado.addItem(i+"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombrePlanta = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        lotes = new javax.swing.JComboBox<>();
        labelFecha = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        fechaCreacion = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        cambiar = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        cancelarConfirm = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modificar estado de lote:");

        labelNombre.setText("Nombre de la planta");

        consultar.setText("Consultar");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consultarMousePressed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarMousePressed(evt);
            }
        });

        lotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotesActionPerformed(evt);
            }
        });

        labelFecha.setText("Fecha de creación:");

        labelEstado.setText("Estado actual:");

        cambiar.setText("Cambiar");
        cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiarMousePressed(evt);
            }
        });

        error.setForeground(new java.awt.Color(255, 0, 51));
        error.setText("Error");

        cancelarConfirm.setText("Cancelar");
        cancelarConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarConfirmMousePressed(evt);
            }
        });

        confirmar.setText("Confirmar");
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(nombrePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFecha)
                                .addGap(23, 23, 23)
                                .addComponent(fechaCreacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelarConfirm)
                                .addGap(18, 18, 18)
                                .addComponent(confirmar))
                            .addComponent(lotes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelar)
                                .addGap(32, 32, 32)
                                .addComponent(consultar)
                                .addGap(29, 29, 29)
                                .addComponent(cambiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEstado)
                                .addGap(82, 82, 82)
                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(error))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre))
                .addGap(18, 18, 18)
                .addComponent(lotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(fechaCreacion)
                    .addComponent(cancelarConfirm)
                    .addComponent(confirmar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar)
                    .addComponent(cancelar)
                    .addComponent(cambiar))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMousePressed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelarMousePressed

    private void consultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMousePressed
        controlador.procesaEventoIntroduceNombrePlanta();
    }//GEN-LAST:event_consultarMousePressed

    private void lotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotesActionPerformed
        controlador.procesaEventoNuevoLoteSeleccionado();
    }//GEN-LAST:event_lotesActionPerformed

    private void cambiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarMousePressed
        cambiar.setVisible(false);
        error.setVisible(false);
        labelEstado.setVisible(false);
        labelFecha.setVisible(false);
        lotes.setVisible(false);
        estado.setVisible(false);
        fechaCreacion.setVisible(false);
        consultar.setVisible(false);
        cancelar.setVisible(false);

        if(estado.getSelectedItem().equals(3)){
            //realiza el CU “Actualización de estimación de flores disponibles”
        }
        
        cancelarConfirm.setVisible(true);
        confirmar.setVisible(true);
        
    }//GEN-LAST:event_cambiarMousePressed

    private void cancelarConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarConfirmMousePressed
        cambiar.setVisible(true);
        consultar.setVisible(false);
        labelEstado.setVisible(true);
        labelFecha.setVisible(true);
        lotes.setVisible(true);
        estado.setVisible(true);
        fechaCreacion.setVisible(true);
        cancelar.setVisible(true);
        
        cancelarConfirm.setVisible(false);
        confirmar.setVisible(false);
    }//GEN-LAST:event_cancelarConfirmMousePressed

    private void confirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMousePressed
        controlador.procesaEventoNuevoEstadoSeleccionado();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_confirmarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarConfirm;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel error;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JLabel fechaCreacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JComboBox<String> lotes;
    private javax.swing.JTextField nombrePlanta;
    // End of variables declaration//GEN-END:variables

    public String getNombre() {
        return nombrePlanta.getText();
    }

    public void mostrarError(String msg) {
        error.setText(msg);
        error.setVisible(true);
    }

    public void añadirLote(String lote) {
        lotes.addItem(lote);
    }

    public void mostrarLotes() {
        labelNombre.setVisible(false);
        nombrePlanta.setVisible(false);
        cambiar.setVisible(true);
        consultar.setVisible(false);
        labelEstado.setVisible(true);
        labelFecha.setVisible(true);
        lotes.setVisible(true);
        estado.setVisible(true);
        fechaCreacion.setVisible(true);
    }

    public void mostrarDatosLote(String fecha, String estadoSel) {
        fechaCreacion.setText(fecha);
        for (int i = 0; i < estado.getItemCount(); i++) {
            if(estado.getItemAt(i).equals(estadoSel)){
                estado.setSelectedIndex(i);
            }
        }
    }
    
    public int getLoteSeleccionado(){
        return Integer.parseInt(lotes.getSelectedItem().toString());
    }
    
    public int getEstadoSeleccionado(){
        return Integer.parseInt(estado.getSelectedItem().toString());
    }
    
    public int getIndexLoteSeleccionado(){
        return lotes.getSelectedIndex();
    }
}
